---
apiVersion: v1
kind: Secret
metadata:
  name: system-info-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: ssh://git@github.com/lroquec/k8s_nginx.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACABUXb4piu1drM0Fs24+5h96cArkoPH/XSMUY/HZlijWAAAAJBpcYFdaXGB
    XQAAAAtzc2gtZWQyNTUxOQAAACABUXb4piu1drM0Fs24+5h96cArkoPH/XSMUY/HZlijWA
    AAAEDpYFHCFojv0kec+w/26bDJlnK+EJJl8CnlX6VRhHFYKwFRdvimK7V2szQWzbj7mH3p
    wCuSg8f9dIxRj8dmWKNYAAAAC2xhdXJhQHRlbWlzAQI=
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "false"
