---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-info-app
  namespace: argocd
  # The following annotations are used by the ArgoCD Image Updater if you don't include manifest updates in your CI/CD pipeline.
  annotations:
    argocd-image-updater.argoproj.io/image-list: system-info-app=lroquec/system-info
    argocd-image-updater.argoproj.io/system-info-app.update-strategy: newest-build
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ssh://git@github.com/lroquec/k8s_nginx.git
    path: k8s
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
